apiVersion: v1
kind: PeristentVolumeClaim
metadata:
  name: nfs-pvc-master
  namespace: storage
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
